= labelify

labelify is a small Python command line application that analyses a given RDF graph (a file) and prints a list of IRIs for subjects and/or predicates and/or objects that don't have labels.

Example command line use:

[source,shell]
----
labelify tests/one/data-access-rights.ttl -c tests/one/background -l https://schema.org/name,http://www.w3.org/2004/02/skos/core\#
----

The above call analyses data-access-rights.ttl in the tests folder of this repository for labels for all s, p & o and looks within the RDF files in tests/one/background to find them. It treats the `skos:prefLabel` predicate as indicating labels as well as the default `rdfs:label`

Example Python script use:

[source,python]
----
from labelify import get_missing_labels
from rdflib import Graph
from rdflib.namespace import RDFS, SKOS
import glob

g = Graph().parse("tests/one/data-access-rights.ttl")
cg = Graph()
for c in glob.glob("tests/one/background/*.ttl"):
    cg.parse(c)

missing = get_missing_labels(
    g,
    cg,
    [SKOS.prefLabel, RDFS.label],
    "objects"
)
print(missing)
----

As per the command line script further above, this use within a Python script looks for missing labels within the RDF file tests/one/data-access-rights.ttl, supplying any that it can from tests/one/background/ and treating `skos:prefLabel` and `rdfs:label` as labelling predicates.

Full command line usage documentation:

[source,shell]
----
usage: labelify [-h] [-v] [-c CONTEXT] [-s {true,false}] [-l LABELS] [-n {subjects,predicates,objects,all}] [-e {true,false}] input

positional arguments:
  input                 Input RDF file being analysed

options:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  -c CONTEXT, --context CONTEXT
                        A folder path containing RDF files or a single RDF file path to the ontology(ies) containing labels for the input
  -s {true,false}, --supress {true,false}
                        Produces no output if set to 'true'. This is used for testing only
  -l LABELS, --labels LABELS
                        A list of predicates (IRIs) to looks for that indicate labels. A comma-delimited list may be supplied or the path of a file containing labelling IRIs, one per line
                        may be supplied. Default is RDFS.label
  -n {subjects,predicates,objects,all}, --nodetype {subjects,predicates,objects,all}
                        The type of node you want to check for labels. Select 'subject', 'predicate', 'object' or 'all'
  -e {true,false}, --evaluate {true,false}
                        Evaluate nodes in the context graphs for labels
----

== Installation

This tool uses Python's https://python-poetry.org/[Poetry] dependency manager so you can load the necissary dependencies into a Python virtual environment by running `python poetry install` in the root directory of this repository.

After that, the `labelify` command line tool will work, on Linux/Mac.

== License

BSB 3-clause, if anyone is asking.

== Development

=== Install Python dependencies

[source,shell]
----
poetry install
----

=== Run tests

[source,shell]
----
poetry run pytest
----

=== Format codebase

[source,shell]
----
poetry run black . && poetry run ruff check --fix labelify/
----

== Contact

*KurrawongAI* +
info@kurrawong.ai +
https://kurrawong.ai
